dasherizing propertyType issue (similar to pull #1961) (#1962)
This is very similar to pull request #1961

If you agree with the changes proposed in that request, you'll probably want to bring these changes in as well. 

If I copy the code for mirage/config.js with propertyType in rentals - I receive an error during testing along the lines of: 

Error: Assertion Failed: Your payload for 'rental' contains 'propertyType', but your serializer is setup to look for 'property-type'. This is most likely because Ember Data's JSON API serializer dasherizes attribute keys by default. You should subclass JSONAPISerializer and implement 'keyForAttribute(key) { return key; }' to prevent Ember Data from customizing your attribute keys.

Pageloads of http://localhost:4200/rentals produce empty pages

Changing propertyType to "property-type" (including quotes) fixes the issue.