dasherizing propertyType to avoid serializer issue (#1961)
At the completion of the "Using Ember Data" page of the tutorial (https://guides.emberjs.com/v2.13.0/tutorial/ember-data/), I receive the following error message when I try to test my ember app: 

Error: Assertion Failed: Your payload for 'rental' contains 'propertyType', but your serializer is setup to look for 'property-type'. This is most likely because Ember Data's JSON API serializer dasherizes attribute keys by default. You should subclass JSONAPISerializer and implement 'keyForAttribute(key) { return key; }' to prevent Ember Data from customizing your attribute keys.

In mirage/config.js if we change propertyType to "property-type" (quotes included) the site works again.

The changes to mirage/config.js were added earlier in the tutorial, on the "Installing Addons" page.